import os
import smtplib
import json
import boto3
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from botocore.exceptions import ClientError

class EmailService:
    """
    Service for sending emails via SMTP using Gmail.
    Credentials are fetched from AWS Secrets Manager.
    """
    def __init__(self):
        # FEEDBACK_SECRET_ID should be set in environment. 
        # Defaulting to the name generated by Terraform for easier local development.
        self.secret_id = os.environ.get("FEEDBACK_SECRET_ID", "KnowYourMLA-feedback-credentials-prod")
        self.aws_region = os.environ.get("AWS_REGION", "ap-south-2")
        self.client = boto3.client("secretsmanager", region_name=self.aws_region)

    def _get_credentials(self):
        """
        Fetches Gmail credentials from AWS Secrets Manager.
        """
        try:
            response = self.client.get_secret_value(SecretId=self.secret_id)
            if "SecretString" in response:
                return json.loads(response["SecretString"])
            return None
        except ClientError as e:
            print(f"Error fetching secret: {e}")
            return None

    def send_feedback(self, message: str, url: str) -> bool:
        """
        Sends feedback via email.

        Args:
            message: The user's feedback message.
            url: The page URL where the feedback was submitted.

        Returns:
            True if sent successfully, False otherwise.
        """
        creds = self._get_credentials()
        if not creds:
            return False

        username = creds.get("username")
        password = creds.get("password")

        if not username or not password:
            return False

        # Create the email message
        msg = MIMEMultipart()
        msg["From"] = username
        msg["To"] = "ptsntamil1@gmail.com" # Updated recipient for feedback
        msg["Subject"] = f"User Feedback from KnowYourMLA"

        body = f"""
        User Feedback:
        --------------------------------------------------
        {message}
        --------------------------------------------------
        
        Submitted from URL: {url}
        """
        msg.attach(MIMEText(body, "plain"))

        try:
            # Connect to Gmail SMTP server
            server = smtplib.SMTP("smtp.gmail.com", 587)
            server.starttls()
            server.login(username, password)
            text = msg.as_string()
            server.sendmail(username, "ptsntamil1@gmail.com", text)
            server.quit()
            return True
        except Exception as e:
            print(f"Error sending email: {e}")
            return False
